version: '3.8'

services:
  trainer-server:
    image: nemo_qr_v1:latest
    container_name: trainer-server
    network_mode: host
    volumes:
      - ./:/app
    environment:
      - MEMORY_CORE_URL=http://localhost:5010
      - PORT=8001
      - TF_CPP_MIN_LOG_LEVEL=2
      - LLM_STUDIO_ENDPOINT=http://host.docker.internal:1234/v1/chat/completions
    command: bash -c "pip install -q fastapi uvicorn aiohttp pydantic tensorflow pandas && python fix_numpy.py python -m synthians_memory_core.synthians_trainer_server.http_server"

  context-cascade-orchestrator:
    image: nemo_qr_v1:latest
    container_name: context-cascade-orchestrator
    network_mode: host
    volumes:
      - ./:/app
    environment:
      - MEMORY_CORE_URL=http://localhost:5010
      - TRAINER_URL=http://localhost:8001
      - NEURAL_MEMORY_URL=http://localhost:8001
    command: bash -c "pip install -q fastapi uvicorn aiohttp pydantic tensorflow && python -m uvicorn synthians_memory_core.orchestrator.server:app --host 0.0.0.0 --port 8002"
    depends_on:
      - trainer-server
