version: '3.8'

services:
  livekit:
    image: livekit/livekit-server
    container_name: livekit-server
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    environment:
      LIVEKIT_KEYS: "devkey: secret"
    volumes:
      - ./config/livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml --bind 0.0.0.0
    networks:
      - lucid-net

  quickrecal:
    image: nemo_qr_v1:latest
    container_name: quickrecal
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/workspace/project
      - LIVEKIT_URL=ws://livekit:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
    volumes:
      - ./:/workspace/project
      - ./memory:/app/memory
      - ${MODELS_PATH}:/workspace/models
    expose:
      - 5001
      - 5005
      - 5410
      - 6006
      - 8888
    ports:
      - "5001:5001"
      - "5005:5005"
      - "5410:5410"
      - "6006:6006"
      - "8888:8888"
    networks:
      - lucid-net
    command: >
      bash -c "pip uninstall -y numpy && pip install numpy==1.24.3 && 
      pip install websockets sentence-transformers scikit-learn==1.3.2 && 
      (/opt/nvidia/nvidia_entrypoint.sh python /workspace/project/server/tensor_server.py &) && 
      /opt/nvidia/nvidia_entrypoint.sh python /workspace/project/server/hpc_server.py"
    tty: true
    stdin_open: true
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864

  port-forward-5000:
    image: alpine/socat
    container_name: port-forward-5000
    depends_on:
      - quickrecal
    command: tcp-listen:5000,fork,reuseaddr tcp-connect:quickrecal:5000
    network_mode: host

  port-forward-5004:
    image: alpine/socat
    container_name: port-forward-5004
    depends_on:
      - quickrecal
    command: tcp-listen:5005,fork,reuseaddr tcp-connect:quickrecal:5005
    network_mode: host

  port-forward-5410:
    image: alpine/socat
    container_name: port-forward-5410
    depends_on:
      - quickrecal
    command: tcp-listen:5410,fork,reuseaddr tcp-connect:quickrecal:5410
    network_mode: host

  luciddream:
    container_name: luciddream
    image: nemo_qr_v1:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    volumes:
      - ./:/workspace/project
      - ./memory:/app/memory
      - ./data:/workspace/data
      - ${MODELS_PATH}:/workspace/models
    networks:
      - lucid-net
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/workspace/project
      - TENSOR_SERVER_URL=ws://quickrecal:5001
      - HPC_SERVER_URL=ws://quickrecal:5005
      - DREAM_API_PORT=8080
      - LOG_LEVEL=INFO
      - LUCIDIA_STORAGE_PATH=/app/memory
      - LLM_API_ENDPOINT=http://host.docker.internal:1234/v1
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - quickrecal
    command: >
      bash -c "pip uninstall -y numpy && pip install numpy==1.24.3 && 
               pip install websockets sentence-transformers scikit-learn==1.3.2 torch==2.0.1 fastapi uvicorn && 
               /opt/nvidia/nvidia_entrypoint.sh python /workspace/project/server/dream_api_server.py"
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864

  stt_transcription:
    container_name: stt_transcription
    image: nemo_qr_v1:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/workspace/project
      - MODELS_PATH=/workspace/models
      - LIVEKIT_URL=ws://livekit-server:7880
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY:-devkey}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET:-secret}
      - HPC_SERVER_URL=ws://quickrecal:5005
      - STT_SERVER_PORT=5002
    volumes:
      - .:/workspace/project
      - ${MODELS_PATH}:/workspace/models
      - ./setup_stt.sh:/workspace/setup_stt.sh
      - ./patch_nemo.py:/workspace/project/patch_nemo.py
      - ./fix_nemo.py:/workspace/project/fix_nemo.py
    networks:
      - lucid-net
    ports:
      - "5002:5002"
    command: >
      bash -c "chmod +x /workspace/setup_stt.sh && /workspace/setup_stt.sh"
    depends_on:
      - livekit

networks:
  lucid-net:
    driver: bridge
