version: '3.8'

services:
  livekit:
    image: livekit/livekit-server
    container_name: livekit-server
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    environment:
      LIVEKIT_KEYS: "devkey: secret"
    volumes:
      - ./config/livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml --bind 0.0.0.0
    networks:
      - lucid-net

  synthians_core:
    image: nemo_qr_v1:latest
    container_name: synthians_core
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/workspace/project
      - LIVEKIT_URL=ws://livekit:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
      - MEMORY_STORAGE_PATH=/app/memory/stored/synthians
      - EMBEDDING_DIM=768
      - GEOMETRY_TYPE=hyperbolic
      - EMBEDDING_MODEL=sentence-transformers/all-mpnet-base-v2
      - EMOTION_MODEL_PATH=/app/models/emotion
      - LOG_LEVEL=INFO
      - HOST=0.0.0.0
      - PORT=5010
      - PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu118
    volumes:
      - ./:/workspace/project
      - ./memory:/app/memory
      - ./models/emotion:/app/models/emotion
      - ${MODELS_PATH}:/workspace/models
      - emotion_model_cache:/root/.cache/huggingface
    expose:
      - 5010
    ports:
      - "5010:5010"
    networks:
      - lucid-net
    command: ["bash", "-c", "cd /workspace/project && ./docker-entrypoint.sh python -m synthians_memory_core.api.server"]
    tty: true
    stdin_open: true
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864

# stt_transcription service has been removed to use Local STT only

networks:
  lucid-net:
    driver: bridge

volumes:
  emotion_model_cache:
