version: '3.8'

services:
  livekit:
    image: livekit/livekit-server
    container_name: livekit-server
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    environment:
      LIVEKIT_KEYS: "devkey: secret"
    volumes:
      - ./config/livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml --bind 0.0.0.0
    networks:
      - lucid-net

  nemo_sig_v3:
    image: lucid-recall-core
    container_name: nemo_sig_v3
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/workspace/project
      - LIVEKIT_URL=ws://livekit:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
    volumes:
      - ./:/workspace/project
      - ${MODELS_PATH}:/workspace/models
    expose:
      - 5001
      - 5005
      - 5410
      - 6006
      - 8888
    ports:
      - "5001:5001"
      - "5005:5005"
      - "5410:5410"
      - "6006:6006"
      - "8888:8888"
    networks:
      - lucid-net
    command: >
      bash -c "pip install websockets sentence-transformers &&
      (/opt/nvidia/nvidia_entrypoint.sh python /workspace/project/server/tensor_server.py &) &&
      /opt/nvidia/nvidia_entrypoint.sh python /workspace/project/server/hpc_server.py"
    tty: true
    stdin_open: true
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864

  port-forward-5000:
    image: alpine/socat
    container_name: port-forward-5000
    depends_on:
      - nemo_sig_v3
    command: tcp-listen:5000,fork,reuseaddr tcp-connect:nemo_sig_v3:5000
    network_mode: host

  port-forward-5004:
    image: alpine/socat
    container_name: port-forward-5004
    depends_on:
      - nemo_sig_v3
    command: tcp-listen:5005,fork,reuseaddr tcp-connect:nemo_sig_v3:5005
    network_mode: host

  port-forward-5410:
    image: alpine/socat
    container_name: port-forward-5410
    depends_on:
      - nemo_sig_v3
    command: tcp-listen:5410,fork,reuseaddr tcp-connect:nemo_sig_v3:5410
    network_mode: host

networks:
  lucid-net:
    driver: bridge
