version: '3.8'

services:
  livekit:
    image: livekit/livekit-server
    container_name: livekit-server
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    environment:
      LIVEKIT_KEYS: "devkey: secret"
    volumes:
      - ./config/livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml --bind 0.0.0.0
    networks:
      - lucid-net

  synthians_core:
    image: nemo_qr_v1:latest
    container_name: synthians_core
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/workspace/project
      - LIVEKIT_URL=ws://livekit:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
      - MEMORY_STORAGE_PATH=/app/memory/stored/synthians
      - EMBEDDING_DIM=768
      - GEOMETRY_TYPE=hyperbolic
      - EMBEDDING_MODEL=sentence-transformers/all-mpnet-base-v2
      - EMOTION_MODEL_PATH=/app/models/emotion
      - LOG_LEVEL=INFO
      - HOST=0.0.0.0
      - PORT=5010
      - LLM_STUDIO_ENDPOINT=http://host.docker.internal:1234/v1/chat/completions
      - PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu118
    volumes:
      - ./:/workspace/project
      - ./memory:/app/memory
      - ./models/emotion:/app/models/emotion
      - ${MODELS_PATH}:/workspace/models
      - emotion_model_cache:/root/.cache/huggingface
    expose:
      - 5010
    ports:
      - "127.0.0.1:5020:5010"  # Use a different port on the host to avoid conflicts
    networks:
      - lucid-net
    # Use the faiss_setup_entrypoint.sh script for proper FAISS GPU initialization
    command: |
      bash /workspace/project/faiss_setup_entrypoint.sh python -m synthians_memory_core.api.server
    tty: true
    stdin_open: true
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864

  # New service for trainer-server with NumPy compatibility fix
  trainer-server:
    image: nemo_qr_v1:latest
    container_name: trainer-server
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/workspace/project
      - LIVEKIT_URL=ws://livekit:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
      - MEMORY_CORE_URL=http://synthians_core:5010
      - EMBEDDING_DIM=768
      - LOG_LEVEL=INFO
      - HOST=0.0.0.0
      - PORT=8001
      - PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu118
    volumes:
      - ./:/workspace/project
      - ./docker-numpy-fix.sh:/app/docker-numpy-fix.sh
      - ${MODELS_PATH}:/workspace/models
      - emotion_model_cache:/root/.cache/huggingface
    expose:
      - 8001
    ports:
      - "8001:8001"
    networks:
      - lucid-net
    # Use the faiss_setup_entrypoint.sh script for proper FAISS GPU initialization
    command: |
      bash /workspace/project/faiss_setup_entrypoint.sh python /workspace/project/trainer_launcher.py
    tty: true
    stdin_open: true
    depends_on:
      - synthians_core
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864

  context-cascade-orchestrator:
    image: nemo_qr_v1:latest
    container_name: context-cascade-orchestrator
    volumes:
      - ./:/app
      - ./orchestrator_entrypoint.sh:/orchestrator_entrypoint.sh
      - ./models:/app/models
    environment:
      - MEMORY_CORE_URL=http://synthians_core:5010
      - NEURAL_MEMORY_URL=http://trainer-server:8001
      - CCE_DEV_MODE=true
      - TITANS_VARIANT=NONE
      - LLM_STUDIO_ENDPOINT=http://host.docker.internal:1234/v1/chat/completions
      - DISABLE_LLM_ROUTER=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["bash", "/orchestrator_entrypoint.sh"]
    ports:
      - "8002:8002"
    networks:
      - lucid-net
    depends_on:
      - synthians_core
      - trainer-server

# stt_transcription service has been removed to use Local STT only

networks:
  lucid-net:
    driver: bridge

volumes:
  emotion_model_cache:

